### ISSUE TITLE
Grid artifacts with isosurfaces rendering

### ISSUE THREAD

**Issue by MengjiaoH** [openvkl/openvkl#1]
Same with https://github.com/ospray/ospray/issues/384

The artifacts were fixed by changing the CELL_WIDTH_BITCOUNT to larger value bigger than the volume dimensions.

**Comment by Twinklebear** [comment]
Also in the picture notice the other grid strip artifacts that show up on the isosurface as well, I've added some highlights to @MengjiaoH 's original screenshot in yellow

![image](https://user-images.githubusercontent.com/1522476/69106266-0ca17200-0a2b-11ea-80c7-b1cb180ea696.png)

**Comment by gregjohnson** [comment]
Thanks for reporting the issue. I'll look into reproducing / debugging this locally.

**Comment by gregjohnson** [comment]
Can you tell me the following?

- which version of OSPRay and Open VKL you're using
- the grid parameters: gridOrigin, gridSpacing
- the isovalue from your example

**Comment by MengjiaoH** [comment]
I am using OSPRay 2.0 and openvkl on release branch. The grid parameter was
as default. And iso value was 0.1.

**Comment by gregjohnson** [comment]
Thanks, I'm able to reproduce. Working on a fix now.

**Comment by gregjohnson** [comment]
We have a fix for the grid strip artifacts (highlighted in yellow above), which is under review and should be available in devel soon.

**Comment by MengjiaoH** [comment]
Thanks!
I will checkout when it’s available.

**Comment by gregjohnson** [comment]
Both types of artifacts highlighted above should now be resolved in the v0.8.0 release. For reference, here are before and after images of my reproducer on that data set:

Before (v0.7.0):
![before_fix](https://user-images.githubusercontent.com/730038/71206583-8450ff80-226a-11ea-927a-e399c27fb3df.png)

After (v0.8.0):
![after_fix](https://user-images.githubusercontent.com/730038/71206602-903cc180-226a-11ea-8833-ad9899aa97b0.png)

Please let me know if you see any further issues.
