### ISSUE TITLE
vklGetValueRange(VKLVolume volume) on a volume with multiple attributes is limited to the first attribute. 

### ISSUE THREAD

**Issue by sudhanshusane** [openvkl/openvkl#10]
Although volumes can support multiple attributes, the current implementation appears to limit the get value range function to returning results for the first attribute associated with the volume. 

vkl_range1f vklGetValueRange(VKLVolume volume);

It would be useful to support get value range for multiple attributes - perhaps by index - in order to support development of multivariate data visualization algorithms.

**Comment by gregjohnson** [comment]
Thanks for your feedback; we'll look into this.

**Comment by gregjohnson** [comment]
We've updated the API to:

`vkl_range1f vklGetValueRange(VKLVolume volume, unsigned int attributeIndex)`

This is available now in `devel` (https://github.com/openvkl/openvkl/commit/2c74957dc661993628ea6622fe0c0b416eb513d8) and will be part of the next release.
