### ISSUE TITLE
zlib-1.2.11.tar.gz has moved on the zlib.net site (superbuild)

### ISSUE THREAD

**Issue by eloop** [openvkl/openvkl#15]
The zlib dependency currently fails for the superbuild as the 1.2.11 version has moved on www.zlib.net. Maybe point at https://www.zlib.net/fossils/zlib-1.2.12.tar.gz so the dependency continues to work across zlib version updates.

**Comment by gregjohnson** [comment]
Thanks for the report, I'll look into this.
