### ISSUE TITLE
A rodent in the front page image...

### ISSUE THREAD

**Issue by paulmelis** [openvkl/openvkl#2]
What the heck is this thing, guys? :)

![ss](https://user-images.githubusercontent.com/1408287/69724558-705b2780-111c-11ea-8877-fab44ff18aa1.jpg)

**Comment by BruceCherniak** [comment]
It wasn't a rock, it was a Rock... Lobster...

Artifact of the scene conversion to pbrt. Up close, it’s actually a ball of coral-type goo. Best to leave it alone.  And wisely choose camera positions that crop it out.

**Comment by paulmelis** [comment]
I guess we can close this :)
