### ISSUE TITLE
Access to cell when sampling

### ISSUE THREAD

**Issue by xuanhuang1** [openvkl/openvkl#3]
Can we have some way to access the cell itself when sampling? I'm trying to use an unstructured volume with an attribute that isn't supposed to be linearly interpolated. 

Or some interface for customized interpolation function?

**Comment by gregjohnson** [comment]
For unstructured volumes, you can specify cell-valued data to avoid any form of interpolation (i.e. specify `cell.data` instead of `vertex.data`. Does this work for your needs?

We don't yet provide functionality to change / customize interpolation functions.

**Comment by gregjohnson** [comment]
Closing this issue. Please let us know if the cell-valued data solution (which eliminates interpolation) does not work for your needs.
