### ISSUE TITLE
Volume with multiple attributes

### ISSUE THREAD

**Issue by xuanhuang1** [openvkl/openvkl#4]
Would be nice to allow that. For now I guess I have to duplicate the volume.

**Comment by paulmelis** [comment]
Would you still use only one attribute for rendering, or do you need a combination (e.g. vector magnitude) to base the rendered value on?

**Comment by xuanhuang1** [comment]
Yeah I need both attribute for rendering. The second one is the result from some topological analysis, stored one each vertex, and I'll need that information together with the vertex value itself (first attribute) to decide the color.

**Comment by Opioid** [comment]
Multiple attributes would be useful for rendering. E.g. a density and an emissive value. Or spectrally varying collision coefficients, that might be used to render certain colored glass, plastics, or mixed fluids.

**Comment by gregjohnson** [comment]
We are now looking into multi-attribute volume support.

**Comment by gregjohnson** [comment]
We introduced API support for multi-attribute volumes in v0.11.0: https://github.com/openvkl/openvkl/releases/tag/v0.11.0

Initially only the structured volume types (`structuredRegular` and `structuredSpherical`) support multi-attribute data. We'll be extending this to other volume types progressively.

**Comment by gregjohnson** [comment]
In the v0.12.0 release we extended multi-attribute support to also include `vdb` volumes. If multi-attribute support is needed for additional volume types, please let us know.
