### ISSUE TITLE
Provide checksum/hashes for superbuild dependencies

### ISSUE THREAD

**Issue by jpg85** [openvkl/openvkl#5]
Please provide checksums for superbuild dependencies:
https://cmake.org/cmake/help/latest/module/ExternalProject.html

This makes building on systems without an Internet connection easier.

**Comment by gregjohnson** [comment]
Thanks for reporting; we're looking into this.

**Comment by gregjohnson** [comment]
We're now providing hashes for all Superbuild dependencies in v0.9.0 (just released). Please let us know if you have any further issues.
